C-3 - Configure Webpack
easycodeguides/codeguides pull request #3
Opened 2020-01-26 21:16 UTC by ZarkoZivojnovic

webpack, babel and react setup

2020-01-26 22:38 UTC, ban17 approved these changes
Everything ok. Just when you are adding content to folders no need to keep .gitkeep anymore, and for webpack if you want to change output folder to build you can add parameter when running webpack but anyway it's ok with default.

2020-01-27 22:53 UTC, ban17 requested changes
Maybe to add test script now.
Also what about typescript support?
Other than that it's very good.

2020-01-28 20:01 UTC, ban17 approved these changes
GTG

2020-01-28 20:14 UTC, janko1031 approved these changes

2020-01-28 21:15 UTC, merged